mail_account:
  smtp: smtp.gmail.com
  email: philipp.kretzschmar@gmail.com
  password: collar:troop42
  port: 465
  useSSL: true
  useTLS: false

sender:
  email: philipp.kretzchmar@gmail.com
  name: Philipp Kretzschmar

test_mail_recievers:
  recievers:
    -
      firstname: Philipp
      lastname: Kretzschmar
      gender: neutral
      email: wolle212@gmail.com
    -
      firstname: Jarael
      lastname: Dafoe
      gender: female
      email: philipp.kretzschmar@gmail.com

content:
  genderfoo:
    male: Mister
    female: Madame
  subject: >
    This is the subject
  content: >
    This is the content of your mail. Be careful with your words ;)
  signature: >
    Keep it short.
  attachements: ~